blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.blog, name="index"),
    url(r'^trash$', views.trash, name="trash"),
    url(r'^(?P<question_id>[0-9]+)$', views.detail, name="detail"),
    url(r'^home$', views.home, name="home"),
    url(r'^add$', views.add, name="add"),
    url(r'^(?P<category>[\w]+)$', views.category, name="category"),
    url(r'^(?P<question_id>[0-9]+)/edit$', views.edit, name="edit"),
    url(r'^(?P<question_id>[0-9]+)/delete$', views.delete, name="delete"),
    url(r'^(?P<question_id>[0-9]+)/comment$', views.comment, name="comment"),
    url(r'^(?P<question_id>[0-9]+)/like$', views.like, name="like"),
    url(r'^(?P<question_id>[0-9]+)/share$', views.share, name="share"),
    url(r'^edit_comment/(?P<comment_id>[0-9]+)$', views.edit_comment, name="edit_comment"),
    url(r'^del_comment/(?P<comment_id>[0-9]+)$', views.del_comment, name="del_comment"),
]

tuxfun/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'tuxfun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

class Post(models.Model):
    post_title = models.CharField(max_length=255)
    post_text = models.TextField()
    pub_date = models.DateTimeField()
    mod_date = models.DateTimeField()
    active  = models.BooleanField(default = True)
    category = models.CharField(max_length=50, default="linux")
    likes = models.IntegerField(default=0)
    shares = models.IntegerField(default=0)

    def __unicode__(self):
        return self.post_title

class Comment(models.Model):
    comment_text = models.CharField(max_length=140)
    pub_date = models.DateTimeField()
    mod_date = models.DateField()
    post = models.ForeignKey(Post)
    active = models.BooleanField(default = True)

    def __unicode__(self):
        return self.comment_text

blog/forms.py
from django import forms

class PostAddition(forms.Form):
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    category = 

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator


def blog(request):
    posts_list = Post.objects.filter(active=1).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    # breadcrumb feed
    link = reverse('blog:home')
    link1 = reverse('blog:index')

    # block aside feeds
    recent_5_posts = posts_list[:5]
    recent_5_fun = posts_list.filter(category='fun')[:5]

    context = {'posts':posts, 'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               }

    return render(request, 'blog/index.html', context)

def home(request):
    return render(request, 'blog/home.html')

def trash(request):
    posts_list = Post.objects.filter(active=0).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/trash.html', {'posts':posts})

def category(request, category):
    posts_list = Post.objects.filter(active=1, category=category).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    # breadcrumb feed
    link = reverse('blog:home')
    link1 = reverse('blog:index')

    # block aside feeds
    recent_5_posts = posts_list[:5]
    recent_5_fun = posts_list.filter(category='fun')[:5]

    context = {'posts':posts, 'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               }

    return render(request, 'blog/index.html', context)

def detail(request, question_id):
    post = get_object_or_404(Post, pk=question_id)
    comments = post.comment_set.filter(active=1).order_by('-pub_date')
    return render(request, 'blog/detail.html', {'post':post,'comments':comments})

def add(request):
    if request.method == "GET":
        return render(request, 'blog/add.html')

    elif request.method == "POST":
        now = timezone.now()
        p = Post(post_title=request.POST['post_title'],\
                 post_text=request.POST['post_text'],\
                 pub_date=now,mod_date=now,\
                 category=request.POST['category']
                 )
        p.save()

        return HttpResponseRedirect(reverse('blog:index'))

def edit(request, question_id):
    now = timezone.now()
    post = Post.objects.get(pk=question_id)
    if request.method == "GET":
        return render(request, 'blog/edit.html', {'post':post})

    else:
        post.post_title = request.POST['post_title']
        post.post_text = request.POST['post_text']
        post.mod_date = now
        post.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))
        # return HttpResponse(post.save())

def delete(request, question_id):
    post = Post.objects.get(pk=question_id)
    post.active = False
    post.save()
    return HttpResponseRedirect(reverse('blog:index'))

def comment(request, question_id):
    if request.method == "GET":
        return HttpResponseRedirect(reverse('blog:detail', args=(question_id,)))

    elif request.method == "POST":
        now = timezone.now()
        post = get_object_or_404(Post, pk=question_id)
        post.comment_set.create(comment_text=request.POST['comment'],pub_date=now,mod_date=now)

        return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))


def like(request, question_id):
    post = get_object_or_404(Post, pk=question_id)
    post.likes += 1
    post.save()
    return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))

def share(request, question_id):
    post = get_object_or_404(Post, pk= question_id)
    post.pub_date = timezone.now()
    post.shares += 1
    post.save()
    return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))


def edit_comment(request, comment_id):
    now = timezone.now()
    comment = Comment.objects.get(pk=comment_id)
    post_id = comment.post_id
    if request.method == "GET":
        return render(request, 'blog/edit_comment.html', {'comment':comment})

    else:
        comment.comment_text = request.POST['comment']
        comment.mod_date = now
        comment.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(post_id,)))


def del_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post_id = comment.post_id
    comment.active = False
    comment.save()
    return HttpResponseRedirect(reverse('blog:detail', args=(post_id,)))

blog/templates/blog/add.html
{% extends 'blog/base.html' %}

{% block content %}
  <article>
    <form action="{% url 'blog:add' %}" method="post">
      {% csrf_token %}
      <input class="form-control" type="text" name="post_title" placeholder="Title" required>
      <label for="category">Category</label>
      <select class="form-control" name="category">
        <option value="linux">Linux</option>
        <option value="programming">Programming</option>
        <option value="web">Web</option>
        <option value="thoughts">Thoughts</option>
        <option value="fun">Fun</option>
      </select> <br>
      	<div id="toolbar">
          <button class="ql-bold">Bold</button>
          <button class="ql-italic">Italic</button>
      	</div>
        <div  id="editor" class="form-control"  cols="3" type="text" name="post_text" placeholder="Write new blog post..." required>
        </div><br>
      <button class="form-control btn btn-info" type="submit">Publish</button>
    </form>
  </article>

{% endblock %}

{% block aside %}
  <h2>Popular on Tuxfun</h2>

  {% for post in recent_5_posts %}
    <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}

  <h2>Popular fun articles</h2>
  {% for post in recent_5_fun  %}
    <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}
{% endblock %}

blog/templates/blog/base.html
<!doctype html>
<html>
  <head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tuxfun Home - Linux and Programming News</title>
    <link rel='stylesheet' href="{% static 'blog/bootstrap/bootstrap.min.css' %}" >
    <link rel='stylesheet' href="{% static 'blog/quill.snow.css' %}">
    <link rel='stylesheet' href="{% static 'blog/main.css' %}">
    <link rel='stylesheet' href="{% static 'blog/font-awesome.min.css' %}">
    <meta charset="utf-8">
  </head>
  <body>

    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#blog-menu">
            <span class="sr-only">Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:home' %}">TuxFun</a>
        </div>

        <div class="collapse navbar-collapse" id="blog-menu">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'blog:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            <li><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-time"></span> Recent</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'blog:category' 'linux' %}"><span class="glyphicon glyphicon-cog"></span> Linux</a></li>
                <li><a href="{% url 'blog:category' 'programming' %}"><span class="glyphicon glyphicon-stats"></span> Programming</a></li>
                <li><a href="{% url 'blog:category' 'web' %}"><span class="glyphicon glyphicon-globe"></span> Web</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:category' 'thoughts' %}"><span class="glyphicon glyphicon-flag"></span> Thoughts</a></li>
                <li><a href="{% url 'blog:category' 'fun' %}"><span class="glyphicon glyphicon-user"></span> Fun</a></li>
              </ul>
            </li>
            <li><a href="{% url 'blog:add' %}"><span class="glyphicon glyphicon-pencil"></span> Add Blog</a></li>
            <li><a href="{% url 'blog:trash' %}"><span class="glyphicon glyphicon-trash"></span> Trash</a></li>
          </ul>
        </div>

      </nav>

    </header>

    <div class="page-header">

    </div>

      <div class="container">

        <!-- <ul class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li><a href="#">Blog</a></li>
        </ul> -->

        <div class="row">
          <div class="col-md-9">
            {% block content %}

            {% endblock %}
          </div>

          <div class="col-md-3 col-sm-3">
            {% block aside %}
              <p><a href=#>Recents</a></p>
              <p><a href=#>Archive</a></p>
              <p><a href=#>About</a></p>
              <p><a href=#>Contacts</a></p>
            {% endblock %}
          </div>
        </div>

      </div>

    </div>
    <script src="{% static 'blog/jquery.min.js' %}"></script>
    <script src="{% static 'blog/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/quill.js' %}"></script>

    {# initialise Quil Editor #}
    <script>
      var editor = new Quill('#editor', {
        modules: { toolbar: '#toolbar' },
        theme: 'snow'
      });
      //prevent quill submit on toolbar click
      $('#toolbar').on('click', 'button', function(e) { e && e.preventDefault() })
    </script>

  </body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
    {% block content %}
          {% if posts %}
          <article>
              {% for post in posts %}
                <content>
                  <h3>{{ post.id }}: <a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a>
                    {% if post.shares >= 1 %}
                    (shared)
                    {% endif %}
                  </h3>
                  from <a href="{% url 'blog:category' post.category %}">{{ post.category|lower }} </a>
                  <small><strong>Posted {{ post.pub_date }}</small></strong> <br>
                </content>
                <content>
                  <img class="thumbnail" src="#" title="post title" alt="make the post more attractive">
                  <p>{{ post.post_text|truncatewords:"30" }}...<p><br>
                </content>
                <content>
                  <p>
                     <a href="{% url 'blog:like' post.id %}"><span title="love" class="glyphicon glyphicon-heart-empty"></span></a>
                     <a href="{% url 'blog:comment' post.id %}"><span class="glyphicon glyphicon-comment"></span></a>
                     <a href="{% url 'blog:share' post.id %}"><span class="glyphicon glyphicon-retweet"></span></a>
                  </p>
                  <hr>
                </content>
              {% endfor %}
            </article>
          {% else %}
            <article>
               <content>
                 <p>No Posts Yet</p>
               </content>
            </article>
          {% endif %}

          <ul class="pagination">
            {% if posts.has_previous %}
              <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
            {% endif %}
            {% for pg in posts.paginator.page_range %}

              {% if posts.number == pg %}
                  <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
              {% else %}
                <li><a href="?page={{ pg }}">{{ pg }}</a></li>
              {% endif %}

              {% endfor %}
              {% if posts.has_next %}
                <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
              {% endif %}
          </ul>


    {% endblock %}

    {% block aside %}
      <h2>Popular on Tuxfun</h2>

      {% for post in recent_5_posts %}
        <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
      {% endfor %}

      <h2>Popular fun articles</h2>
      {% for post in recent_5_fun  %}
        <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
      {% endfor %}
    {% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <article>
    {% if post %}
        <content>
          <h3>{{ post.id }}: <a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></h3>
          from <a href="{% url 'blog:category' post.category %}">{{ post.category|lower }} </a>
          <small><strong>Posted {{ post.pub_date }}</small></strong> |
          <a href="{% url 'blog:edit' post.id  %}" title="Edit Post"><span class="glyphicon glyphicon-pencil"></span> Edit Post</a> |
          <a href="{% url 'blog:delete' post.id %}"><span class="glyphicon glyphicon-trash"></span> Delete</a> <br>
        </content>
        <content>
          <img class="thumbnail" src="#" title="post title" alt="make the post more attractive">
          <p>{{ post.post_text }}<p><br>
        </content>
        <content>
          <p>
             <a href="{% url 'blog:like' post.id %}"><span title="love" class="glyphicon glyphicon-heart-empty">{{ post.likes }}</span></a>|
             <a href="{% url 'blog:comment' post.id %}"><span class="glyphicon glyphicon-comment">{{ post.comment_set.count }}</span></a>|
             <a href="{% url 'blog:share' post.id %}"><span class="glyphicon glyphicon-retweet">{{ post.shares }}</span></a>
          </p>
          <hr>
        </content>

      {# <form action="./comment" method="post">#}
      {% block comment_form %}
      <form action="{% url 'blog:comment' post.id %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="comment" placeholder="comment..." required><br>
        <button class="form-control btn btn-info" type="submit">Publish</button>
      </form>
      {% endblock %}

      <section>
        {% if post.comment_set.all.0 != None %}
          {% for comment in comments %}
            <p>{{ comment.comment_text }} <strong><small>{{ comment.pub_date }}</small></strong>
                 <a href="{% url 'blog:edit_comment' comment.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                 <a href="{% url 'blog:del_comment' comment.id %}"><span class="glyphicon glyphicon-trash"></span></a>
            </p>
          {% endfor %}
        {% else %}
          <p> No comments yet!</p>
        {% endif %}
      </section>
    {% else %}
      <p>Post not found.Back <a href="{% url 'blog:index' %}">Home</a> </p>
    {% endif %}
  </article>

{% endblock %}

{% block aside %}
  <h2>Popular on Tuxfun</h2>

  {% for post in recent_5_posts %}
    <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}

  <h2>Popular fun articles</h2>
  {% for post in recent_5_fun  %}
    <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}
{% endblock %}

blog/templates/blog/edit.html
{% extends 'blog/index.html' %}

{% block content %}
  {% if post %}
    <article>
      <form action="{% url 'blog:edit' post.id %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="post_title" value="{{ post.post_title }}"  required></br>
        <textarea class="form-control" type="text" name="post_text"  required>{{ post.post_text }}</textarea></br>
        <button class="form-control btn btn-info" type="submit">Publish</button>
      </form>
    </article>
  {% else %}
    <p>Send Default Data to form</p>
  {% endif %}

{% endblock %}

{% block aside %}
  <h2>Popular on Tuxfun</h2>

  {% for post in recent_5_posts %}
    <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}

  <h2>Popular fun articles</h2>
  {% for post in recent_5_fun  %}
    <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
  {% endfor %}
{% endblock %}

blog/templates/blog/edit_comment.html
{% extends 'blog/index.html' %}

{% block content %}
	<form action="{% url 'blog:edit_comment' comment.id %}" method="post">
		{% csrf_token %}
		<input class="form-control" type="text" name="comment" value="{{ comment.comment_text }}" required><br>
		<button class="form-control btn btn-info" type="submit">Publish</button>
	</form>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}

      <div class='jumbotron'>
        <h1>You are at Tuxfun!</h1>
        <p>Here, Programming, Linux, OpenSource and the Web are Always Fun!</p>
        <button class="btn btn-link btn-info"><a href="{% url 'blog:index' %}">Learn more</a></button>
      </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
    {% block content %}
          {% if posts %}
            <article>
              {% for post in posts %}
                <content>
                  <h3>{{ post.id }}: <a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a>
                    {% if post.shares >= 1 %}
                    (shared)
                    {% endif %}
                  </h3>
                  from <a href="{% url 'blog:category' post.category %}">{{ post.category|lower }} </a>
                  <small><strong>Posted {{ post.pub_date }}</small></strong> <br>
                </content>
                <content>
                  <img class="thumbnail" src="#" title="post title" alt="make the post more attractive">
                  <p>{{ post.post_text|truncatewords:"30" }}...<p><br>
                </content>
                <content>
                  <p>
                     <a href="{% url 'blog:like' post.id %}"><span title="love" class="glyphicon glyphicon-heart-empty">{{ post.likes }}</span></a>|
                     <a href="{% url 'blog:comment' post.id %}"><span class="glyphicon glyphicon-comment">{{ post.comment_set.count }}</span></a>|
                     <a href="{% url 'blog:share' post.id %}"><span class="glyphicon glyphicon-retweet">{{ post.shares }}</span></a>
                  </p>
                  <hr>
                </content>
              {% endfor %}
            </article>
          {% else %}
            <article>
               <content>
                 <p>No Posts Yet</p>
               </content>
            </article>
          {% endif %}

            <ul class="pagination">
              {% if posts.has_previous %}
                <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
              {% endif %}
              {% for pg in posts.paginator.page_range %}

                {% if posts.number == pg %}
                    <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                  <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endif %}

                {% endfor %}
                {% if posts.has_next %}
                  <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>

    {% endblock %}

    {% block aside %}
      <h2>Popular on Tuxfun</h2>

      {% for post in recent_5_posts %}
        <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
      {% endfor %}

      <h2>Popular fun articles</h2>
      {% for post in recent_5_fun  %}
        <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
      {% endfor %}
    {% endblock %}

blog/templates/blog/trash.html
{% extends 'blog/index.html' %}